/**
 * Global App Configuration
 * This file should be loaded before any other script.
 * In production, this can be generated by CI/CD or served dynamically.
 */
window.AppConfig = {
    // Current Environment: 'http://192.168.0.34:8084'
    API_BASE_URL: 'http://192.168.0.34:8084'
};
